version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo logging in to Amazon ECR
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d6p5p7z0

  build:
    commands:
      - echo building docker image
      - docker build -t 3-tier-backend /backend
      - docker tag 3-tier-backend:latest public.ecr.aws/d6p5p7z0/3-tier-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION
      
  post_build:
    commands:
      - echo Pushing image to docker image to Amazon ECR
      - docker push public.ecr.aws/d6p5p7z0/3-tier-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION

