apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/d6p5p7z0/3-tier-frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://k8s-workshop-mainlb-7f430e3450-1403177756.us-west-2.elb.amazonaws.com/api/tasks" 
        ports:
        - containerPort: 3000

